# Generated by Django 4.2.9 on 2024-01-14 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=150, verbose_name='место')),
                ('time', models.TimeField(verbose_name='время')),
                ('action', models.CharField(max_length=150, verbose_name='действие')),
                ('is_nice', models.BooleanField(default=False, verbose_name='приятная привычка')),
                ('period', models.PositiveIntegerField(verbose_name='периодичность (в днях)')),
                ('reward', models.CharField(blank=True, max_length=150, null=True, verbose_name='вознаграждение')),
                ('time_to_do', models.PositiveIntegerField(verbose_name='время на выполнение (сек)')),
                ('is_public', models.BooleanField(default=False, verbose_name='публичная привычка')),
            ],
            options={
                'verbose_name': 'привычка',
                'verbose_name_plural': 'привычки',
            },
        ),
        migrations.CreateModel(
            name='HabitSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_date_send', models.DateTimeField(auto_now_add=True, verbose_name='Следующая дата отправки')),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motivator.habit', verbose_name='привычка')),
            ],
            options={
                'verbose_name': 'Подписка на привычки',
                'verbose_name_plural': 'Подписки на привычки',
            },
        ),
    ]
